Repository zurichat/zc_app, pull requests merged in 2021-09, with the labels that each got.

#838 Add People to Channel Conflict Resolved
  lib/models/add_people_model.dart
  lib/models/static_user_model.dart
  lib/models/user_search_model.dart
  lib/package/base/server-request/channels/channels_api_service.dart
  lib/package/base/server-request/organization_request/organization_api_service.dart
  lib/services/api_service.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/nav_pages/home_page/widgets/zuri_logo.dart
  lib/ui/view/channel/add_people/channel_add_people_view.dart
  lib/ui/view/channel/add_people/channel_add_people_viewmodel.dart
  lib/ui/view/channel/channel_info/channel_info_view_model.dart
  lib/ui/view/channel/channel_info/widgets/textstyles.dart
  lib/ui/view/channel/channel_info/widgets/third_section.dart
  lib/ui/view/channel/channel_list/channel_page.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_view.form.dart
  lib/ui/view/draft/app/data.dart
  lib/ui/view/draft/app/drafted_item_widget.dart
  lib/ui/view/draft/draft_view.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
  pubspec.lock
Labels: Accepted

#824 dmJumpToView UI adjustment made, ChannelInfo UI redesigned and Errors fixed
  flutter
  lib/app/app.dart
  lib/app/app.router.dart
  lib/general_widgets/custom_channel.dart
  lib/general_widgets/custom_channel_stage.dart
  lib/general_widgets/custom_user.dart
  lib/general_widgets/custom_user_channel.dart
  lib/models/channels_search_model.dart
  lib/ui/nav_pages/home_page/home_page.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/shared/bottom_sheets/custom_user_bottomsheet/custom_user_bottom_sheet_viewmodel.dart
  lib/ui/shared/colors.dart
  lib/ui/shared/setup_bottom_sheet_ui.dart
  lib/ui/shared/styles.dart
  lib/ui/view/channel/channel_info/channel_info_view.dart
  lib/ui/view/channel/channel_info/channel_info_view_model.dart
  lib/ui/view/channel/channel_info/widgets/custom_app_bar.dart
  lib/ui/view/channel/channel_info/widgets/fifth_section.dart
  lib/ui/view/channel/channel_info/widgets/first_section.dart
  lib/ui/view/channel/channel_info/widgets/fourth_section.dart
  lib/ui/view/channel/channel_info/widgets/newRowTile.dart
  lib/ui/view/channel/channel_info/widgets/second_section.dart
  lib/ui/view/channel/channel_info/widgets/sixth_section.dart
  lib/ui/view/channel/channel_info/widgets/third_section.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/dm_chat_view/dm_jump_to_view.dart
  lib/ui/view/dm_chat_view/dm_jump_to_viewmodel.dart
  lib/ui/view/forgot_password/forgot_password_otp/forgot_password_otpview.dart
  pubspec.lock~e532f9e99f92288efa68551c4a034ec3c156894d
Labels: Pending Review

#846 fixed label build flutter version
  .github/workflows/build_apk.yml
  .github/workflows/code_and test_ analyzer.yml
Labels: Accepted

#849 API Abstract Class implemented
  lib/app/app.dart
  lib/app/app.locator.dart
  lib/package/base/jump_to_request/jump_to_api.dart
  lib/package/base/server-request/api/api.dart
  lib/package/base/server-request/api/http_api.dart
  lib/package/base/server-request/api/zuri_api.dart
  lib/package/base/server-request/channels/channels_api_service.dart
  lib/package/base/server-request/dms/dms_api_service.dart
  lib/package/base/server-request/organization_request/organization_api_service.dart
  lib/services/current_user_profile.dart
  lib/services/theme_setup.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/shared/bottom_sheets/custom_user_bottomsheet/custom_user_bottom_sheet_viewmodel.dart
  lib/ui/shared/bottom_sheets/profile_botton_sheet/custom_user_bottom_sheet_viewmodel.dart
  lib/ui/view/channel/add_people/channel_add_people_viewmodel.dart
  lib/ui/view/channel/channel_info/channel_info_view_model.dart
  lib/ui/view/channel/channel_list/channels_viewmodel.dart
  lib/ui/view/channel/edit_channel/editChannelViewModel.dart
  lib/ui/view/dm_chat_view/dm_jump_to_viewmodel.dart
  lib/ui/view/edit_profile/edit_profile_viewmodel.dart
  lib/ui/view/forgot_password/forgot_password_email/forgot_password_email_viewmodel.dart
  lib/ui/view/forgot_password/forgot_password_new_password/forgot_password_newviewmodel.dart
  lib/ui/view/forgot_password/forgot_password_otp/forgot_password_otpviewmodel.dart
  lib/ui/view/login/login_viewmodel.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
  lib/ui/view/otp/otp_viewmodel.dart
  lib/ui/view/sign_up/sign_up_viewmodel.dart
  lib/ui/view/start_dm/start_dm_viewmodel.dart
  pubspec.lock~e532f9e99f92288efa68551c4a034ec3c156894d
Labels: Changes requested

#825 Preference in Organization list
  lib/ui/view/organization/organization_view/organization_view.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
Labels: Pending Review
