Repository zurichat/zc_app, pull requests merged in 2021-10, with the labels that each got.

#865 Delete channel and Expanded textfield
  .fvm/flutter_sdk
  .fvm/fvm_config.json
  .vscode/settings.json
  assets/icons/svg_icons/at_sign.svg
  assets/icons/svg_icons/camera.svg
  assets/icons/svg_icons/maximize.svg
  assets/icons/svg_icons/minimize.svg
  assets/icons/svg_icons/paperclip.svg
  assets/icons/svg_icons/smile.svg
  assets/icons/svg_icons/zap.svg
  lib/general_widgets/expandable_textfield.dart
  lib/package/base/server-request/api/api.dart
  lib/package/base/server-request/api/zuri_api.dart
  lib/package/base/server-request/channels/channels_api_service.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/nav_pages/home_page/widgets/home_list_items.dart
  lib/ui/shared/smart_widgets/expandable_textfield/expandable_textfield_screen.dart
  lib/ui/shared/smart_widgets/expandable_textfield/expandable_textfield_screen_viewmodel.dart
  lib/ui/view/channel/channel_info/channel_info_view.dart
  lib/ui/view/channel/channel_info/channel_info_view_model.dart
  lib/ui/view/channel/channel_info/widgets/sixth_section.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/channel/channel_view/widgets/channel_reply_box.dart
  lib/ui/view/dm_user/dm_user_view.dart
  lib/ui/view/dm_user/dm_user_viewmodel.dart
  lib/ui/view/dm_user/icons/zap_icon.dart
  lib/ui/view/splashscreen/splashscreen_viewmodel.dart
  lib/ui/view/threads/thread_detail/thread_detail_view.dart
  test/helpers/test_helpers.mocks.dart
Labels: Pending Review

#871 feat: Channel Threads(Add and receive replies)
  lib/models/app_model.dart
  lib/models/user_post.dart
  lib/package/base/server-request/api/zuri_api.dart
  lib/package/base/server-request/channels/channels_api_service.dart
  lib/services/connectivity_service.dart
  lib/ui/shared/smart_widgets/thread_card/thread_card_viewmodel.dart
  lib/ui/shared/smart_widgets/thread_card/widgets/thread_card_main.dart
  lib/ui/shared/smart_widgets/thread_card/widgets/thread_card_post.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/channel/channel_view/widgets/channel_chat.dart
  lib/ui/view/dm_user/icons/zap_icon.dart
  lib/ui/view/threads/all_threads/widgets/thread_card.dart
  lib/ui/view/threads/thread_detail/thread_detail_view.dart
  lib/ui/view/threads/thread_detail/thread_detail_viewmodel.dart
  lib/utilities/storage_keys.dart
  pubspec.yaml
Labels: Pending Review, Conflict

#872 Channel Message Error Checking
  lib/general_widgets/no_connection_widget.dart
  lib/services/connectivity_service.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/dm_user/dm_user_view.dart
  lib/ui/view/dm_user/widgets/custom_start_message.dart
  lib/ui/view/dm_user/widgets/online_indicator.dart
Labels: Pending Review

#879 Implement Adding Members To A Channel
  lib/app/app.router.dart
  lib/models/user_search_model.dart
  lib/package/base/server-request/api/dio_interceptors.dart
  lib/package/base/server-request/api/zuri_api.dart
  lib/package/base/server-request/channels/channels_api_service.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/view/channel/add_people/channel_add_people_view.dart
  lib/ui/view/channel/add_people/channel_add_people_viewmodel.dart
  lib/ui/view/channel/channel_list/channel_page.dart
  lib/ui/view/channel/channel_list/channels_viewmodel.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/channel/channel_view/widgets/channel_intro.dart
Labels: Changes requested

#848 RegEx Update for Text parser
  lib/ui/shared/smart_widgets/text_parser/text_parser_viewmodel.dart
  lib/utilities/utilities.dart
  test/services/text_parser_test.dart
Labels: Pending Review

#876 unit tests for advanced_viewmodel and channel_add_people viewmodel
  test/helpers/test_helpers.dart
  test/helpers/test_helpers.mocks.dart
  test/view_models/advanced_viewmodel_test.dart
  test/view_models/channel_add_people_viewmodel_test.dart
Labels: Conflict

#886 Project-wide strings extraction 3/3
  lib/constants/app_strings.dart
  lib/ui/shared/bottom_sheets/custom_user_bottomsheet/custom_user_bottom_sheet_view.dart
  lib/ui/view/do_not_disturb/do_not_disturb_viewmodel.dart
  lib/ui/view/draft/app/data.dart
  lib/ui/view/draft/draft_view.dart
  lib/ui/view/draft/draft_viewmodel.dart
  lib/ui/view/draft/drafts.dart
  lib/ui/view/edit_profile/edit_profile_view.dart
  lib/ui/view/edit_profile/edit_profile_viewmodel.dart
  lib/ui/view/feedback_alert_dialog/feed_back_dialog.dart
  lib/ui/view/file_search/file_search_view.dart
  lib/ui/view/file_search/widgets/search_bar.dart
  lib/ui/view/language_and_region/language_and_region_view.dart
  lib/ui/view/language_and_region/language_and_region_viewmodel.dart
  lib/ui/view/notifications/notifications_view.dart
  lib/ui/view/onboarding/onboading_view.dart
  lib/ui/view/organization/add_organization/add_organization_view.dart
  lib/ui/view/organization/create_organization/company.dart
  lib/ui/view/organization/create_organization/create_organization.dart
  lib/ui/view/organization/create_organization/create_organization_viewmodel.dart
  lib/ui/view/organization/create_organization/invite.dart
  lib/ui/view/organization/create_organization/project.dart
  lib/ui/view/organization/email_confirmation/email_confirmation_view.dart
  lib/ui/view/organization/email_confirmation/email_confirmation_viewmodel.dart
  lib/ui/view/organization/new_email/new_email.dart
  lib/ui/view/organization/organization_different_email/different_email_organization_view.dart
  lib/ui/view/organization/organization_url/organization_url_view.dart
  lib/ui/view/organization/organization_view/organization_view.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
  lib/ui/view/organization/select_email/select_email_viewmodel.dart
  lib/ui/view/pinned_messages/pinned_message.dart
  lib/ui/view/set_status/set_status_view.dart
  lib/ui/view/splashscreen/splashscreen.dart
  lib/ui/view/start_dm/start_dm_view.dart
  lib/ui/view/start_dm/widgets/custom_chip_input.dart
  lib/ui/view/start_dm/widgets/custom_input_chip.dart
  lib/ui/view/threads/all_threads/threads_view.dart
  lib/ui/view/threads/all_threads/widgets/thread_card.dart
  lib/ui/view/threads/thread_detail/thread_detail_view.dart
  lib/ui/view/threads/thread_detail/thread_detail_viewmodel.dart
  lib/ui/view/user_search/user_search_not_found.dart
  lib/ui/view/view_profile_page/view_profile.dart
Labels: Pending Review

#887 Unit tests for all forget password and login view models
  pubspec.lock
  test/helpers/test_helpers.dart
  test/services/connectivity_service_test.dart
  test/view_models/forgot_password_email_viewmodel_test.dart
  test/view_models/forgot_password_new_viewmodel_test.dart
  test/view_models/forgot_password_otp_viewmodel_test.dart
  test/view_models/login_viewmodel_test.dart
  test/view_models/otp_viewmodel_test.dart
Labels: Changes requested

#883 Unit tests for the DMUserViewModel, DmJumpToViewModel, NotificationsViewModel and PluginViewModel.
  lib/ui/nav_pages/you_page/you_page_view.dart
  lib/ui/shared/bottom_sheets/profile_botton_sheet/custom_user_bottom_sheet_view.dart
  lib/ui/shared/bottom_sheets/profile_botton_sheet/widgets/profile_head.dart
  lib/ui/view/direct_message/direct_message.dart
  lib/ui/view/direct_message/direct_message_text_field_hook.dart
  lib/ui/view/direct_message/direct_message_viewmodel.dart
  lib/ui/view/dm_user/dm_user_viewmodel.dart
  lib/ui/view/nav_bar/nav_bar_view.dart
  lib/ui/view/plugins/plugin_viewmodel.dart
  lib/ui/view/plugins/plugins_view.dart
  lib/ui/view/plugins/widgets/custom_appbar.dart
  pubspec.lock~af9caa46d6ea233e66b0af348da124f4f9edb4fb
  pubspec.yaml
  test/helpers/test_helpers.dart
  test/view_models/dm_jump_to_viewmodel_test.dart
  test/view_models/dm_user_viewmodel_test.dart
  test/view_models/notifications_viewmodel_test.dart
  test/view_models/plugin_viewmodel_test.dart
Labels: Changes requested

#898 Passed Channel data and Update Channel Details Implementation
  lib/app/app.router.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/channel/channel_view/widgets/channel_intro.dart
  lib/ui/view/channel/edit_channel/edit_channel_view.dart
  lib/ui/view/channel/edit_channel/edit_channel_view_model.dart
  lib/ui/view/channel/edit_channel/widgets/edit_channel_appbar.dart
  lib/ui/view/channel/edit_channel/widgets/edit_channel_text_field.dart
  test/helpers/test_helpers.mocks.dart
Labels: Changes requested

#920 Implemented SignOut From All Organization.
  assets/language/en.json
  assets/language/es.json
  assets/language/fr.json
  assets/language/it.json
  assets/language/nl.json
  assets/language/pt.json
  assets/language/zh.json
  lib/constants/app_strings.dart
  lib/constants/local_keys.dart
  lib/main.dart
  lib/services/local_storage_services.dart
  lib/ui/nav_pages/home_page/home_page.dart
  lib/ui/nav_pages/you_page/you_page.dart
  lib/ui/nav_pages/you_page/you_page_viewmodel.dart
  lib/ui/shared/bottom_sheets/sign_out_bottomsheet/sign_out_botton_sheet_viewmodel.dart
  lib/ui/view/language_and_region/language_and_region_viewmodel.dart
  lib/ui/view/nav_bar/nav_bar_view.dart
  lib/ui/view/organization/organization_view/organization_view.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
  lib/utilities/constants.dart
  lib/utilities/internalization/language_model.dart
  lib/utilities/internalization/local_setup.dart
  lib/utilities/internalization/localization/app_localization.dart
  lib/utilities/internalization/localization/language_constant.dart
  pubspec.lock
  pubspec.lock~af9caa46d6ea233e66b0af348da124f4f9edb4fb
  pubspec.yaml
Labels: Changes requested

#915 Theme Fixes 1/2
  lib/app/app.locator.dart
  lib/constants/app_strings.dart
  lib/general_widgets/custom_text.dart
  lib/general_widgets/svg_icon.dart
  lib/services/local_storage_services.dart
  lib/services/theme_setup.dart
  lib/ui/nav_pages/dm_page/dm_page.dart
  lib/ui/nav_pages/home_page/home_page.dart
  lib/ui/nav_pages/home_page/widgets/home_list_items.dart
  lib/ui/nav_pages/you_page/widgets/status_form.dart
  lib/ui/shared/bottom_sheets/sign_out_bottomsheet/sign_out_bottom_sheet_view.dart
  lib/ui/shared/bottom_sheets/sign_out_bottomsheet/widgets/work_space_display_info_view.dart
  lib/ui/shared/colors.dart
  lib/ui/shared/dialogs/select_theme_dialog.dart
  lib/ui/shared/dialogs/sign_out_dialog.dart
  lib/ui/shared/styles.dart
  lib/ui/shared/text_styles.dart
  lib/ui/view/forgot_password/forgot_password_email/forgot_password_email_view.dart
  lib/ui/view/forgot_password/forgot_password_new_password/forgot_password_newview.dart
  lib/ui/view/forgot_password/forgot_password_otp/forgot_password_otpview.dart
  lib/ui/view/login/login_view.dart
  lib/ui/view/nav_bar/nav_bar_view.dart
  lib/ui/view/organization/add_organization/add_organization_view.dart
  lib/ui/view/organization/organization_view/organization_view.dart
  lib/ui/view/organization/organization_view/organization_viewmodel.dart
  lib/ui/view/otp/otp_view.dart
  lib/ui/view/preference/preference_view.dart
  lib/ui/view/preference/preference_viewmodel.dart
  lib/ui/view/sign_up/sign_up_view.dart
  lib/ui/view/splashscreen/splashscreen.dart
  lib/utilities/storage_keys.dart
  pubspec.lock
Labels: Pending Review

#919 Make sure the UI of the homepage matches the design and jump to behavior matches the one on slack
  lib/general_widgets/menu_item_tile.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/view/channel/new_channel/new_channel.dart
  lib/ui/view/dm_chat_view/dm_jump_to_view.dart
Labels: Changes requested

#922 Perfecting the draft Implementation
  lib/constants/app_strings.dart
  lib/models/draft_data_holder_model.dart
  lib/ui/nav_pages/home_page/home_page.dart
  lib/ui/nav_pages/home_page/home_page_viewmodel.dart
  lib/ui/nav_pages/home_page/widgets/home_list_items.dart
  lib/ui/shared/dialogs/delete_draft_alert_dialog.dart
  lib/ui/shared/setup_dialog_ui.dart
  lib/ui/shared/smart_widgets/expandable_textfield/expandable_textfield_screen.dart
  lib/ui/shared/styles.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_view.form.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/direct_message/direct_message.dart
  lib/ui/view/direct_message/direct_message.form.dart
  lib/ui/view/direct_message/direct_message_viewmodel.dart
  lib/ui/view/dm_chat_view/dm_jump_to_viewmodel.dart
  lib/ui/view/dm_user/dm_user_view.dart
  lib/ui/view/dm_user/dm_user_view.form.dart
  lib/ui/view/dm_user/dm_user_viewmodel.dart
  lib/ui/view/draft/draft_view.dart
  lib/ui/view/draft/draft_viewmodel.dart
  lib/ui/view/draft/drafts.dart
  lib/ui/view/threads/thread_detail/thread_detail_view.dart
  lib/ui/view/threads/thread_detail/thread_detail_viewmodel.dart
  lib/utilities/enums.dart
  lib/utilities/storage_keys.dart
  pubspec.lock
  pubspec.yaml
Labels: Changes requested

#967 Channel Info Screen UI and all implementations
  lib/app/app.router.dart
  lib/constants/app_strings.dart
  lib/ui/nav_pages/you_page/you_page.dart
  lib/ui/nav_pages/you_page/you_page_viewmodel.dart
  lib/ui/shared/smart_widgets/thread_card/widgets/thread_card_channel_main.dart
  lib/ui/view/channel/channel_info/channel_info_view.dart
  lib/ui/view/channel/channel_info/channel_info_view_model.dart
  lib/ui/view/channel/channel_info/widgets/fifth_section.dart
  lib/ui/view/channel/channel_info/widgets/first_section.dart
  lib/ui/view/channel/channel_info/widgets/fourth_section.dart
  lib/ui/view/channel/channel_info/widgets/second_section.dart
  lib/ui/view/channel/channel_info/widgets/sixth_section.dart
  lib/ui/view/channel/channel_info/widgets/third_section.dart
  lib/ui/view/channel/channel_view/channel_page_view.dart
  lib/ui/view/channel/channel_view/channel_page_viewmodel.dart
  lib/ui/view/channel/edit_channel/edit_channel_view.dart
  pubspec.lock
  test/view_models/channel_info_view_model_test.dart
Labels: Changes requested

#968 Get all icons in the Figma file and replace it in the app
  assets/icons/svg_icons/Add-description.svg
  assets/icons/svg_icons/Channel_Page_Share.svg
  assets/icons/svg_icons/Copy-text.svg
  assets/icons/svg_icons/Mark_Unread.svg
  assets/icons/svg_icons/Reply_In_Thread.svg
  assets/icons/svg_icons/Send.svg
  assets/icons/svg_icons/Shape.svg
  assets/icons/svg_icons/Share_message.svg
  assets/icons/svg_icons/Vector (1).svg
  assets/icons/svg_icons/active.svg
  assets/icons/svg_icons/add-organization.svg
  assets/icons/svg_icons/add-people.svg
  assets/icons/svg_icons/akar-icons_link_chain.svg
  assets/icons/svg_icons/archive.svg
  assets/icons/svg_icons/bell-off.svg
  assets/icons/svg_icons/bell.svg
  assets/icons/svg_icons/bi_chat-text.svg
  assets/icons/svg_icons/bi_pin-angle.svg
  assets/icons/svg_icons/bookmark.svg
  assets/icons/svg_icons/circle.svg
  assets/icons/svg_icons/copy_text.svg
  assets/icons/svg_icons/default.svg
  assets/icons/svg_icons/fluent_camera-16-regular.svg
  assets/icons/svg_icons/fluent_navigation-unread-24-regular.svg
  assets/icons/svg_icons/fluent_send-24-filled.svg
  assets/icons/svg_icons/gg_time.svg
  assets/icons/svg_icons/log-out.svg
  assets/icons/svg_icons/members.svg
  assets/icons/svg_icons/notification.svg
  assets/icons/svg_icons/phone.svg
  assets/icons/svg_icons/pin_conversation.svg
  assets/icons/svg_icons/pinned_message.svg
  assets/icons/svg_icons/plus.svg
  assets/icons/svg_icons/preference.svg
  assets/icons/svg_icons/share.svg
  assets/icons/svg_icons/toggle_off_sharp.svg
  assets/icons/svg_icons/user.svg
  lib/constants/app_strings.dart
  lib/general_widgets/menu_item_tile.dart
  lib/ui/nav_pages/home_page/widgets/home_list_items.dart
  lib/ui/nav_pages/plugin_page/plugin_page_view.dart
  lib/ui/nav_pages/you_page/you_page.dart
  lib/ui/shared/bottom_sheets/thread_options_bottomsheet/thread_options_bottomsheet_view.dart
  lib/ui/shared/bottom_sheets/zuri_chat_bottomsheet.dart
  lib/ui/view/channel/channel_info/widgets/fifth_section.dart
  lib/ui/view/channel/channel_info/widgets/fourth_section.dart
  lib/ui/view/channel/channel_info/widgets/second_section.dart
  lib/ui/view/channel/channel_info/widgets/sixth_section.dart
  lib/ui/view/channel/channel_info/widgets/third_section.dart
  lib/ui/view/channel/channel_view/widgets/channel_intro.dart
  lib/ui/view/expandable_textfield/expandable_textfield_screen.dart
  lib/ui/view/login/login_viewmodel.dart
  lib/ui/view/organization/add_organization/add_organization_view.dart
  lib/ui/view/set_status/widgets/status.dart
Labels: Conflict
